##Задача 1
- Оформляйте ноутбук, используя эти советы:
- Номер задачи - заголовок 2
- Номер подзадачи - заголовок 3
- Предоставленные наборы данных оформляйте, как код

##Задача 2
На складе лежат разные фрукты в разном количестве.
Нужно написать функцию, которая на вход принимает любое количество названий фруктов и их количество, а возвращает общее количество фруктов на складе

In [4]:
def sum_veg(**kwargs):
    sum_fruits = sum(kwargs.values())
    return sum_fruits

a = sum_veg(tomatoes=10, cucumbers=14, eggplants=21)
a

45

##Задача 3
Дан список с затратами на рекламу. Но в данных есть ошибки, некоторые затраты имеют отрицательную величину. Удалите такие значения из списка и посчитайте суммарные затраты
[100, 125, -90, 345, 655, -1, 0, 200]
Используйте list comprehensions

In [10]:
expenses = [100, 125, -90, 345, 655, -1, 0, 200]
sum_expenses =  [i for i in expenses if i > 0]
print(sum(sum_expenses))

1425

##Задача 4
Даны два списка.
Дата покупки
['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24', '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20', '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09', '2021-12-13', '2021-10-26', '2021-12-09']
Суммы покупок по датам
[1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822, 519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

###Задача 4.1
Найдите, какая выручка у компании в ноябре
Используйте list comprehensions

In [16]:
date =  ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24',
         '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20',
         '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09',
         '2021-12-13', '2021-10-26', '2021-12-09']
summa = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822,
         519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]
print(sum([s for d, s in zip(date, summa) if d[5:7] == "11"]))

25098

###Задача 4.2
Найдите выручку компании в зависимости от месяца
Для этого напишите функцию, которая на вход принимает список с датами и список с выручкой, а на выходе словарь, где ключи - это месяцы, а значения - это выручка.
Используйте аннотирование типов.

In [17]:
date =  ['2021-09-14', '2021-12-15', '2021-09-08', '2021-12-05', '2021-10-09', '2021-09-30', '2021-12-22', '2021-11-29', '2021-12-24',
         '2021-11-26', '2021-10-27', '2021-12-18', '2021-11-09', '2021-11-23', '2021-09-27', '2021-10-02', '2021-12-27', '2021-09-20',
         '2021-12-13', '2021-11-01', '2021-11-09', '2021-12-06', '2021-12-08', '2021-10-09', '2021-10-31', '2021-09-30', '2021-11-09',
         '2021-12-13', '2021-10-26', '2021-12-09']
summa = [1270, 8413, 9028, 3703, 5739, 4095, 295, 4944, 5723, 3701, 4471, 651, 7037, 4274, 6275, 4988, 6930, 2971, 6592, 2004, 2822,
         519, 3406, 2732, 5015, 2008, 316, 6333, 5700, 2887]

def sum_in_mon(date: list, summa: list) -> dict:
    res = {}
    for d, s in zip(date, summa):
        if d[5:7] in res.keys():
            res[d[5:7]] = res[d[5:7]] + s
        else:
            res[d[5:7]] = s
    return res

print(sum_in_mon(date, summa))

{'09': 25647, '12': 45452, '10': 28645, '11': 25098}